version: '3.8'

services:
  backend:
    build:
      context: backend
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - app_data:/app/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: frontend
    ports:
      - "8080:8080"
    environment:
      API_BASE_URL: http://backend:8000
    depends_on:
      - backend

volumes:
    app_data: