version: '3.8'

services:
  backend:
    image: ghcr.io/tsai00/datainfrapilotbe:latest
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - app_data:/app/data
    ports:
      - "8000:8000"

  frontend:
    image: ghcr.io/tsai00/datainfrapilotfe:latest
    ports:
      - "8080:8080"
    environment:
      API_BASE_URL: http://backend:8000
    depends_on:
      - backend

volumes:
    app_data: