apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik