apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ certificate_name }}
  namespace: {{ namespace }}
spec:
  secretName: {{ secret_name }}
  dnsNames:
    - {{ domain_name }}
  issuerRef:
    name: acme
    kind: Issuer