apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme
  namespace: kube-system

spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik