class ProjectNotEmptyException(Exception): ...


class ResourceExistsException(Exception): ...


class ResourceUnavailableException(Exception): ...


class NamespaceTerminatedException(Exception): ...
