{
 "title": "Scrapers Monitoring Dashboard",
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": "SELECT DISTINCT project FROM scraper_run_metadata;"
   }
  ]
 },
 "panels": [
  {
   "title": "# Successful Runs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id)\nFROM public.scraper_run_metadata\nWHERE\n  $__timeFilter(start_time) AND\n  project in ($project) AND\n  is_successful = True; "
    }
   ]
  },
  {
   "title": "# Failed Runs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id)\nFROM public.scraper_run_metadata\nWHERE\n  $__timeFilter(start_time) AND\n  project in ($project) AND\n  is_successful = False; "
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (COUNT(CASE WHEN is_successful THEN 1 END) * 100.0) / COUNT(id) AS \"Success Rate\"\nFROM public.scraper_run_metadata\nWHERE\n  $__timeFilter(start_time) AND\n  project in ($project)"
    }
   ]
  },
  {
   "title": "Average Scraping Time (successful)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(EXTRACT(EPOCH FROM (end_time - start_time))) AS \"Avg Duration (s)\"\nFROM public.scraper_run_metadata\nWHERE\n  $__timeFilter(start_time) AND\n  project in ($project) AND\n  is_successful = TRUE AND\n  end_time IS NOT NULL"
    }
   ]
  },
  {
   "title": "Total Pages Processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(pages_total)\nFROM public.scraper_run_metadata\nWHERE is_successful = TRUE AND\nproject in ($project) AND\n$__timeFilter(start_time);\n\n"
    }
   ]
  },
  {
   "title": "Total Items Scraped",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(items_scraped)\nFROM public.scraper_run_metadata\nWHERE\n  $__timeFilter(start_time) AND\n  project in ($project) AND\n  is_successful = TRUE"
    }
   ]
  },
  {
   "title": "Items Scraped vs Items Total Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(start_time, $__interval),\n  SUM(items_scraped) AS \"Items Scraped\",\n  SUM(items_total) AS \"Items Total\"\nFROM public.scraper_run_metadata\nWHERE\n  $__timeFilter(start_time) AND\n  project in ($project) AND\n  is_successful = TRUE AND\n  items_scraped IS NOT NULL\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Run Duration Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(start_time, $__interval),\n  AVG(EXTRACT(EPOCH FROM (end_time - start_time))) AS \"Avg Duration (s)\"\nFROM public.scraper_run_metadata\nWHERE\n  $__timeFilter(start_time) AND\n  project IN ($project) AND\n  is_successful = TRUE AND\n  end_time IS NOT NULL\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Requests Sent (GET vs. POST) Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroup(start_time, $__interval),\n  SUM(get_requests_sent) AS \"GET Requests\",\n  SUM(post_requests_sent) AS \"POST Requests\"\nFROM public.scraper_run_metadata\nWHERE\n  $__timeFilter(start_time) AND\n  project IN ($project) AND\n  get_requests_sent IS NOT NULL\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}