#cloud-config

timezone: Europe/Prague

package_update: true
package_upgrade: true

packages:
  - open-iscsi
  - nfs-client
  - nfs-common

runcmd:
  - >
    curl -sfL https://get.k3s.io | 
    K3S_TOKEN="{{ k3s_token }}" 
    INSTALL_K3S_VERSION="{{ k3s_version }}"
    INSTALL_K3S_EXEC="server \
    --disable local-storage \
    --disable-cloud-controller \
    --disable servicelb \
    --write-kubeconfig-mode=644 \ 
    --node-name=$HOSTNAME \
    --node-label="pool={{ pool_name }}"" sh -
